### ISSUE TITLE
在做备份文件扫描时出现的报错

### ISSUE THREAD

**Issue by S1nK0000** [chainreactors/spray#73]
```./spray_linux_amd64 -l all_target.txt --bak --common > output.txt```

![image](https://github.com/user-attachments/assets/654354be-1366-4f4c-90ff-f3ac62f539ef)
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x8e3f0b]

goroutine 5225 [running]:
github.com/chainreactors/spray/internal/pool.(*BrutePool).doAppendRule.func1()
        /home/runner/work/spray/spray/internal/pool/brutepool.go:521 +0x12b
created by github.com/chainreactors/spray/internal/pool.(*BrutePool).doAppendRule in goroutine 71
        /home/runner/work/spray/spray/internal/pool/brutepool.go:517 +0x88
```

**Comment by M09Ic** [comment]
应该与https://github.com/chainreactors/spray/issues/72 是同一个panic, 我会尽快修复这个bug

**Comment by M09Ic** [comment]
已在v1.1.2 中修复 https://github.com/chainreactors/spray/releases/tag/v1.1.2
